# Generated by Django 3.2.8 on 2021-10-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_todomodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
