# Generated by Django 3.2.8 on 2021-10-26 18:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTPModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('otp', models.IntegerField()),
                ('is_valid', models.BooleanField(default=False)),
                ('expiry_date', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
